# Generated by Django 5.1.3 on 2024-11-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='conutry',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='postal_date',
            new_name='postal_code',
        ),
    ]
